questionList={
	[1]={
		id=1,
		intro = "How many mango trees were there in total?",
		introAnswer1 = "126",
		introAnswer2 = "84",
		introAnswer3 = "98",
		introAnswer3 = "49",
	},
	[2]={
		id=2,
		intro = "Which of the following is the correct sequence of trees received by Abha, Bina, Chitra and Dipti in that order?",
		introAnswer1 = "50, 69, 30, 56",
		introAnswer2 = "60, 39, 40, 66",
		introAnswer3 = "44, 87, 24, 50",
		introAnswer3 = "54, 57, 34, 60",
	},
	[3]={
		id=3,
		intro = "How many pine trees did Chitra receive?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[4]={
		id=4,
		intro = "Who got the plot with the smallest number of trees and how many trees did that plot have?",
		introAnswer1 = "Abha, 4 trees",
		introAnswer2 = "Dipti, 6 trees",
		introAnswer3 = "Bina, 3 trees",
		introAnswer3 = "Bina, 4 trees",
	},
	[5]={
		id=5,
		intro = "Which of the following statements is NOT true?",
		introAnswer1 = "Bina got 32 pine trees.",
		introAnswer2 = "Chitra got 12 mango trees.",
		introAnswer3 = "Abha got 41 teak trees.",
		introAnswer3 = "Dipti got 56 mango trees.",
	},
	[6]={
		id=6,
		intro = "Which column had the highest number of trees?",
		introAnswer1 = "3",
		introAnswer2 = "Cannot be determined",
		introAnswer3 = "2",
		introAnswer3 = "4",
	},
	[7]={
		id=7,
		intro = "What were the bids by Arun, Bankim, Charu and Dipak, respectively in the first round?",
		introAnswer1 = "Hi, Lo, Lo, Lo",
		introAnswer2 = "Lo, Lo, Lo, Hi",
		introAnswer3 = "Hi, Lo, Lo, Hi",
		introAnswer3 = "Hi, Hi, Lo, Lo",
	},
	[8]={
		id=8,
		intro = "In how many rounds did Bankim bid Lo?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[9]={
		id=9,
		intro = "In how many rounds did all four players make identical bids?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[10]={
		id=10,
		intro = "In which of the following rounds, was Arun DEFINITELY the only player to bid Hi?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[11]={
		id=11,
		intro = "Among the following days, the largest fraction of orders booked on which day was lost?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[12]={
		id=12,
		intro = "On which of the following days was the number of orders booked the highest?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[13]={
		id=13,
		intro = "The average time taken to deliver orders booked on a particular day is computed as follows. Let the number of orders delivered the next day be x and the number of orders delivered the day after be y. Then the average time to deliver order is (x+2y)/(x+y). On which of the following days was the average time taken to deliver orders booked the least?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[14]={
		id=14,
		intro = "What was the number of schools having facilities F2 and F4?",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
	[15]={
		id=15,
		intro = "The delivery ratio for a given day is defined as the ratio of the number of orders booked on that day which are delivered on the next day to the number of orders booked on that day which are delivered on the second day after booking. On which of the following days, was the delivery ratio the highest? ",
		introAnswer1 = "15",
		introAnswer2 = "18",
		introAnswer3 = "30",
		introAnswer3 = "21",
	},
}
